name: 'CE.ImageNet.ResNet'
output_dir: './output/imagenet'
valid_step: 1
save_step: -1
show_step: 100
input_size: (224, 224)
color_space: 'RGB'

dataset:
    root: '/home/anonymous/datasets/imagenet'
    dataset: 'ImageNet1k'
    num_classes: 1000

backbone:
    type: 'resnet152_z'
    in_channels: 3

pooling:
    type: 'GlobalAvgPooling'

reshape:
    type: 'FlattenCustom'

classifier:
    type: 'FC'
    bias: True

scaling:
    type: 'Identity'

loss:
    loss_type: 'CrossEntropyCustom'

train:
    batch_size: 256
    num_epochs: 300
    num_workers: 24
    trainer:
        type: 'default'
    optimizer:
        type: 'SGD'
        base_lr: 0.0001
        weight_decay: 1e-4
    lr_scheduler:
        type: 'multistep'
        lr_factor: 0.1
        lr_step: [150, 225]
    tensorboard:
        enable: True

transforms:
    train_transforms: ('resize', 'normalize',)
    test_transforms: ('resize', 'normalize',)
    process_detail:
        normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]

test:
    batch_size: 256
    num_workers: 24
    model_file: 'best_model.pth'

