name: 'NormOrth.FMNIST.VGG11.20epoch'
output_dir: './output/fmnist'
valid_step: 1
save_step: -1
show_step: 100
input_size: (32, 32)
color_space: 'Gray'
cpu_mode: False
ddp: True
port: 12355
seed_num: 0

dataset:
    root: '/data/anonymous'
    dataset: 'FashionMNIST'
    num_classes: 10

backbone:
    type: 'vgg11f_bn_one'

pooling:
    type: 'Identity'

reshape:
    type: 'FlattenNorm'

classifier:
    type: 'OrthLinear'
    bias: False

scaling:
    type: 'Identity'

loss:
    loss_type: 'LogLoss'

train:
    batch_size: 128
    num_epochs: 100
    num_workers: 2
    trainer:
        type: 'default'
    optimizer:
        type: 'SGD'
        base_lr: 0.01
        momentum: 0.9
        weight_decay: 5e-4
    lr_scheduler:
        type: 'multistep'
        lr_step: [20, 40, 60, 80]
        lr_factor: 0.5
    tensorboard:
        enable: True

transforms:
    train_transforms: ('resize', 'random_crop', 'random_horizontal_flip', 'normalize')
    test_transforms: ('resize', 'normalize')
    process_detail:
        normalize:
            mean: [0.286,]
            std: [0.353,]

test:
    batch_size: 256
    num_workers: 2
    model_file: 'best_model.pth'

