name: 'CE.CIFAR100.DenseNet'
output_dir: './output/cifar100'
valid_step: 1
save_step: -1
show_step: 100
input_size: (32, 32)
color_space: 'RGB'

dataset:
    root: '/data/anonymous'
    dataset: 'CIFAR100'
    num_classes: 100

backbone:
    type: 'densenets250_z'
    in_channels: 3

pooling:
    type: 'GlobalAvgPooling'

reshape:
    type: 'FlattenCustom'

classifier:
    type: 'FC'
    bias: True

scaling:
    type: 'Identity'

loss:
    loss_type: 'CrossEntropyCustom'

train:
    batch_size: 128
    num_epochs: 350
    num_workers: 2
    trainer:
        type: 'default'
    optimizer:
        type: 'SGD'
        base_lr: 0.0001
        weight_decay: 5e-4
    lr_scheduler:
        type: 'multistep'
        lr_factor: 0.1
        lr_step: [117, 233]
    tensorboard:
        enable: True

transforms:
    train_transforms: ('normalize',)
    test_transforms: ('normalize',)
    process_detail:
        normalize:
            mean: [0.5071, 0.4865, 0.4409]  # [0.5071, 0.4865, 0.4409]
            std: [0.2673, 0.2564, 0.2762]  # [0.2673, 0.2564, 0.2762]

test:
    batch_size: 256
    num_workers: 2
    model_file: 'best_model.pth'

