name: 'NormOrth.CIFAR100.ResNet18.200epoch'
output_dir: './output/cifar100'
valid_step: 1
save_step: -1
show_step: 100
input_size: (32, 32)
color_space: 'RGB'
cpu_mode: False
ddp: True
port: 12355
seed_num: 0

dataset:
    root: '/data/anonymous'
    dataset: 'CIFAR100'
    num_classes: 100

backbone:
    type: 'resnetcifar18_z'

pooling:
    type: 'GlobalAvgPooling'

reshape:
    type: 'FlattenNorm'

classifier:
    type: 'OrthLinear'
    bias: False

scaling:
    type: 'Identity'

loss:
    loss_type: 'LogLoss'

train:
    batch_size: 128
    num_epochs: 200
    num_workers: 2
    trainer:
        type: 'default'
    optimizer:
        type: 'SGD'
        base_lr: 0.1
        weight_decay: 5e-4
        momentum: 0.9
    lr_scheduler:
        type: 'multistep'
        lr_step: [60, 120, 160]
        lr_factor: 0.2
    tensorboard:
        enable: True

transforms:
    train_transforms: ('random_crop', 'random_horizontal_flip', 'random_rotation', 'normalize')
    test_transforms: ('normalize',)
    process_detail:
        normalize:
            mean: [0.5071, 0.4865, 0.4409]
            std: [0.2673, 0.2564, 0.2762]

test:
    batch_size: 256
    num_workers: 2
    model_file: 'best_model.pth'

