name: 'CE.STL10.ResNet'
output_dir: './output/stl10'
valid_step: 1
save_step: -1
show_step: 100
input_size: (96, 96)
color_space: 'RGB'

dataset:
    root: '/data/anonymous'
    dataset: 'STL10'
    num_classes: 10

backbone:
    type: 'resnets50_z'
    in_channels: 3

pooling:
    type: 'GlobalAvgPooling'

reshape:
    type: 'FlattenCustom'

classifier:
    type: 'FC'
    bias: True

scaling:
    type: 'Identity'

loss:
    loss_type: 'CrossEntropyCustom'

train:
    batch_size: 128
    num_epochs: 350
    num_workers: 2
    trainer:
        type: 'default'
    optimizer:
        type: 'SGD'
        base_lr: 0.0001
        weight_decay: 5e-4
    lr_scheduler:
        type: 'multistep'
        lr_factor: 0.1
        lr_step: [117, 233]
    tensorboard:
        enable: True

transforms:
    train_transforms: ('normalize',)
    test_transforms: ('normalize',)
    process_detail:
        normalize:
#            mean: [0.1307,]  # [0.4467, 0.4398, 0.4066]
#            std: [0.3081,]  # [0.2603, 0.2566, 0.2713]
            mean: [0.4467, 0.4398, 0.4066]
            std: [0.2603, 0.2566, 0.2713]

test:
    batch_size: 256
    num_workers: 2
    model_file: 'best_model.pth'

